name: truthordare
description: "A new Flutter project."
publish_to: 'none'

version: 1.2.1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.3.1
  path_provider: ^2.1.4
  file_selector: ^1.0.3
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  change_app_package_name: ^1.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/challenges/challenges.txt
    - assets/challenges/challenge_categories.json
    - assets/lang/en.json
    - assets/lang/fr.json
    - assets/lang/de.json
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 300
    - family: OpenDyslexic
      fonts:
        - asset: assets/fonts/OpenDyslexic-Regular.otf
          weight: 300
        - asset: assets/fonts/OpenDyslexic-Bold.otf
          weight: 600
        - asset: assets/fonts/OpenDyslexic-Bold.otf
          weight: 800